[tool.poetry]
name = "graph"
version = "0.1.0"
description = "my workspace"
authors = ["Park Jimin <parkjimin788@gmail.com>"]
readme = "README.md"

# 패키지 위치 지정 (src/graph 사용 시)
packages = [{ include = "graph", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.12,<3.14.1"
networkx = "^3.6.1"
python-louvain = "^0.16"
matplotlib = "^3.10.3"
pandas = "2.2.2"
seaborn = "^0.13.2"
pyyaml = "^6.0.2"
charset-normalizer = "^3.4.2"
pyarrow = "^21.0.0"
fastparquet = "^2024.11.0"
ipywidgets = "^8.1.7"
requests = "^2.32.5"
jupyter = "^1.1.1"
ipykernel = "^6.30.1"
textual = "^6.2.1"
plotly = "^6.3.1"
chardet = "^5.2.0"
sqlalchemy = "2.0.23"
psycopg2-binary = "2.9.9"
black = "^25.11.0"
streamlit = "^1.51.0"
pygwalker = "^0.4.9.15"
polars = "^1.35.2"
statsmodels = "^0.14.6"
linearmodels = "^7.0"
playwright = "^1.57.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

